<?php
$heaven11_slider_sc = heaven11_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $heaven11_slider_sc ) && strpos( $heaven11_slider_sc, '[' ) !== false && strpos( $heaven11_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider">
	<?php
		// Add anchor
		$heaven11_anchor_icon = heaven11_get_theme_option( 'front_page_title_anchor_icon' );
		$heaven11_anchor_text = heaven11_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $heaven11_anchor_icon ) || ! empty( $heaven11_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $heaven11_anchor_icon ) ? ' icon="' . esc_attr( $heaven11_anchor_icon ) . '"' : '' )
									. ( ! empty( $heaven11_anchor_text ) ? ' title="' . esc_attr( $heaven11_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $heaven11_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$heaven11_scheme = heaven11_get_theme_option( 'front_page_title_scheme' );
		if ( ! heaven11_is_inherit( $heaven11_scheme ) ) {
			echo ' scheme_' . esc_attr( $heaven11_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( heaven11_get_theme_option( 'front_page_title_paddings' ) );
		?>
		"
		<?php
		$heaven11_css      = '';
		$heaven11_bg_image = heaven11_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $heaven11_bg_image ) ) {
			$heaven11_css .= 'background-image: url(' . esc_url( heaven11_get_attachment_url( $heaven11_bg_image ) ) . ');';
		}
		if ( ! empty( $heaven11_css ) ) {
			echo ' style="' . esc_attr( $heaven11_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$heaven11_anchor_icon = heaven11_get_theme_option( 'front_page_title_anchor_icon' );
		$heaven11_anchor_text = heaven11_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $heaven11_anchor_icon ) || ! empty( $heaven11_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $heaven11_anchor_icon ) ? ' icon="' . esc_attr( $heaven11_anchor_icon ) . '"' : '' )
									. ( ! empty( $heaven11_anchor_text ) ? ' title="' . esc_attr( $heaven11_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( heaven11_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' heaven11-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$heaven11_css      = '';
			$heaven11_bg_mask  = heaven11_get_theme_option( 'front_page_title_bg_mask' );
			$heaven11_bg_color_type = heaven11_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $heaven11_bg_color_type ) {
				$heaven11_bg_color = heaven11_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $heaven11_bg_color_type ) {
				$heaven11_bg_color = heaven11_get_scheme_color( 'bg_color', $heaven11_scheme );
			} else {
				$heaven11_bg_color = '';
			}
			if ( ! empty( $heaven11_bg_color ) && $heaven11_bg_mask > 0 ) {
				$heaven11_css .= 'background-color: ' . esc_attr(
					1 == $heaven11_bg_mask ? $heaven11_bg_color : heaven11_hex2rgba( $heaven11_bg_color, $heaven11_bg_mask )
				) . ';';
			}
			if ( ! empty( $heaven11_css ) ) {
				echo ' style="' . esc_attr( $heaven11_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$heaven11_caption = heaven11_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $heaven11_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $heaven11_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses(( $heaven11_caption ),'heaven11_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$heaven11_description = heaven11_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $heaven11_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $heaven11_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $heaven11_description ), 'heaven11_kses_content' ) ?></div>
					<?php
				}

				// Buttons
				if ( heaven11_get_theme_option( 'front_page_title_button1_link' ) != '' || heaven11_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						heaven11_show_layout( heaven11_customizer_partial_refresh_front_page_title_button1_link() );
						heaven11_show_layout( heaven11_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
